export enum LogType {
  NOVEL_TASK_GET_NOVEL_LAST_PAGE = 'NOVEL_TASK_GET_NOVEL_LAST_PAGE',
  NOVEL_TASK_GET_NOVEL_LAST_ID = 'NOVEL_TASK_GET_NOVEL_LAST_ID',
  NOVEL_TASK_GET_NOVEL_CHAPTER_LAST_PAGE = 'NOVEL_TASK_GET_NOVEL_CHAPTER_LAST_PAGE',
}
